In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt

In [2]:
df = pd.read_csv("online_retail_ii.csv")
df.rename(columns = {'Invoice': 'InvoiceNo', 'Customer ID': 'CustomerID', 'Price': 'UnitPrice'}, inplace=True)
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   InvoiceNo    1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  object
 5   UnitPrice    1067371 non-null  float64
 6   CustomerID   824364 non-null   float64
 7   Country      1067371 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 65.1+ MB

In [4]:
df.describe()

           Quantity     UnitPrice     CustomerID
count  1.067371e+06  1.067371e+06  824364.000000
mean   9.938898e+00  4.649388e+00   15324.638504
std    1.727058e+02  1.235531e+02    1697.464450
min   -8.099500e+04 -5.359436e+04   12346.000000
25%    1.000000e+00  1.250000e+00   13975.000000
50%    3.000000e+00  2.100000e+00   15255.000000
75%    1.000000e+01  4.150000e+00   16797.000000
max    8.099500e+04  3.897000e+04   18287.000000

In [7]:
df = df[df['Quantity']>=0]
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1044420 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   InvoiceNo    1044420 non-null  object
 1   StockCode    1044420 non-null  object
 2   Description  1042727 non-null  object
 3   Quantity     1044420 non-null  int64
 4   InvoiceDate  1044420 non-null  object
 5   UnitPrice    1044420 non-null  float64
 6   CustomerID   805620 non-null   float64
 7   Country      1044420 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 71.7+ MB

In [8]:
df.dropna(axis=0, subset=['InvoiceNo'],inplace=True)
df['InvoiceNo']=df['InvoiceNo'].astype('str')
df = df[~df['InvoiceNo'].str.contains('C')]
df.shape

(1044420, 8)

In [9]:
df['Country'].value_counts()

United Kingdom          961223
EIRE                     17354
Germany                  16703
France                   13941
Netherlands               5093
Spain                     3720
Switzerland               3137
Belgium                   3069
Portugal                  2562
Australia                 1815
Channel Islands           1569
Italy                     1468
Norway                    1437
Sweden                    1338
Cyprus                    1155
Finland                   1032
Austria                    922
Denmark                    798
Unspecified                752
Greece                     657
Poland                     512
Japan                      485
United Arab Emirates       467
USA                        409
Israel                     369
Hong Kong                  358
Singapore                  339
Malta                      282
Iceland                    253
Canada                     228
Lithuania                  189
RSA                        168
Bahrain                    124
Brazil                      94
Thailand                    76
European Community          60
Lebanon                     57
West Indies                 54
Korea                       53
Bermuda                     34
Nigeria                     30
Czech Republic              25
Saudi Arabia                 9
Name: Country, dtype: int64

In [10]:
data = (df[df['Country'] =="United Kingdom"].groupby(['InvoiceNo', 'Description'])['Quantity']
               .sum().unstack().reset_index().fillna(0).set_index('InvoiceNo'))
data.head()

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,tk maxx mix up with pink,to push order througha s stock was,update,website fixed,wrong invc,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
489434,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489435,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489436,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489437,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
489438,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [11]:
data = (data > 0).astype(int)
data

Description,DOORMAT UNION JACK GUNS AND ROSES,3 STRIPEY MICE FELTCRAFT,4 PURPLE FLOCK DINNER CANDLES,50'S CHRISTMAS GIFT BAG LARGE,ANIMAL STICKERS,BLACK PIRATE TREASURE CHEST,BROWN PIRATE TREASURE CHEST,Bank Charges,CAMPHOR WOOD PORTOBELLO MUSHROOM,CHERRY BLOSSOM DECORATIVE FLASK,...,tk maxx mix up with pink,to push order througha s stock was,update,website fixed,wrong invc,wrongly coded 20713,wrongly coded 23343,wrongly marked,wrongly marked 23343,wrongly sold (22719) barcode
InvoiceNo,,,,,,,,,,,,,,,,,,,,,
489434,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489435,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489436,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489437,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
489438,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
A516228,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A528059,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563185,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563186,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
A563187,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [12]:

# ###
# For each item /column  (column_total/36758)
# remove all the values < 0.02
# output1

# for i in output1:
#     for j in output1:
#         Count(df[df[i]==1 and df[j]==1])
# remove all values< 0.02
# output 2




from mlxtend.frequent_patterns import apriori

In [14]:
frequent_itemsets_plus = apriori(data, min_support=0.02, 
                                 use_colnames=True).sort_values('support', ascending=False).reset_index(drop=True)
frequent_itemsets_plus['length'] = frequent_itemsets_plus['itemsets'].apply(lambda x: len(x))

frequent_itemsets_plus

/Users/architsharma/miniconda3/envs/tf/lib/python3.9/site-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

      support                              itemsets  length
0    0.142989  (WHITE HANGING HEART T-LIGHT HOLDER)       1
1    0.093612            (REGENCY CAKESTAND 3 TIER)       1
2    0.082975             (JUMBO BAG RED RETROSPOT)       1
3    0.072039       (ASSORTED COLOUR BIRD ORNAMENT)       1
4    0.068992                       (PARTY BUNTING)       1
..        ...                                   ...     ...
259  0.020104              (LAUNDRY 15C METAL SIGN)       1
260  0.020050      (RED STRIPE CERAMIC DRAWER KNOB)       1
261  0.020050          (PICNIC BASKET WICKER LARGE)       1
262  0.020050     (BLUE STRIPE CERAMIC DRAWER KNOB)       1
263  0.020023           (I'M ON HOLIDAY METAL SIGN)       1

[264 rows x 3 columns]

In [16]:
frequent_itemsets_plus['length'].value_counts()

1    235
2     29
Name: length, dtype: int64

In [15]:
frequent_itemsets_plus.loc[frequent_itemsets_plus.length==2]

      support                                           itemsets  length
72   0.031966  (RED HANGING HEART T-LIGHT HOLDER, WHITE HANGI...       2
90   0.029653  (WOODEN PICTURE FRAME WHITE FINISH, WOODEN FRA...       2
100  0.028783  (JUMBO BAG RED RETROSPOT, JUMBO STORAGE BAG SUKI)       2
122  0.026960  (SWEETHEART CERAMIC TRINKET BOX, STRAWBERRY CE...       2
123  0.026933     (HEART OF WICKER SMALL, HEART OF WICKER LARGE)       2
127  0.026525  (JUMBO SHOPPER VINTAGE RED PAISLEY, JUMBO BAG ...       2
141  0.025464  (ROSES REGENCY TEACUP AND SAUCER , GREEN REGEN...       2
145  0.025029  (JUMBO BAG RED RETROSPOT, JUMBO BAG PINK POLKA...       2
151  0.024484    (JUMBO BAG STRAWBERRY, JUMBO BAG RED RETROSPOT)       2
155  0.024267  (JUMBO  BAG BAROQUE BLACK WHITE, JUMBO BAG RED...       2
161  0.023913  (JUMBO SHOPPER VINTAGE RED PAISLEY, JUMBO STOR...       2
172  0.023124     (LUNCH BAG CARS BLUE, LUNCH BAG  BLACK SKULL.)       2
178  0.022961  (HOME BUILDING BLOCK WORD, LOVE BUILDING BLOCK...       2
179  0.022961  (LUNCH BAG SPACEBOY DESIGN , LUNCH BAG  BLACK ...       2
180  0.022771  (60 TEATIME FAIRY CAKE CASES, PACK OF 60 PINK ...       2
188  0.022471  (WOODEN FRAME ANTIQUE WHITE , WHITE HANGING HE...       2
190  0.022444  (WOODEN PICTURE FRAME WHITE FINISH, WHITE HANG...       2
194  0.022335  (PAPER CHAIN KIT VINTAGE CHRISTMAS, PAPER CHAI...       2
220  0.021329      (LUNCH BAG WOODLAND, LUNCH BAG  BLACK SKULL.)       2
222  0.021193  (GREEN REGENCY TEACUP AND SAUCER, PINK REGENCY...       2
228  0.021029  (JUMBO  BAG BAROQUE BLACK WHITE, JUMBO STORAGE...       2
236  0.020730  (HEART OF WICKER SMALL, WHITE HANGING HEART T-...       2
240  0.020594  (WHITE HANGING HEART T-LIGHT HOLDER, HEART OF ...       2
241  0.020567  (LUNCH BAG SPACEBOY DESIGN , LUNCH BAG CARS BLUE)       2
250  0.020349          (LUNCH BAG WOODLAND, LUNCH BAG CARS BLUE)       2
252  0.020322  (CHOCOLATE HOT WATER BOTTLE, HOT WATER BOTTLE ...       2
254  0.020186     (JUMBO BAG STRAWBERRY, JUMBO STORAGE BAG SUKI)       2
257  0.020159  (ALARM CLOCK BAKELIKE RED , ALARM CLOCK BAKELI...       2
258  0.020159  (VINTAGE SNAP CARDS, VINTAGE HEADS AND TAILS C...       2

In [21]:
from mlxtend.frequent_patterns import association_rules
rules = association_rules(frequent_itemsets_plus, metric ="lift", min_threshold = 1)
rules.head(5)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(RED HANGING HEART T-LIGHT HOLDER),(WHITE HANGING HEART T-LIGHT HOLDER),0.045514,0.142989,0.031966,0.702331,4.911775,0.025458,2.879074,0.834384
1,(WHITE HANGING HEART T-LIGHT HOLDER),(RED HANGING HEART T-LIGHT HOLDER),0.142989,0.045514,0.031966,0.223554,4.911775,0.025458,1.229301,0.929285
2,(WOODEN PICTURE FRAME WHITE FINISH),(WOODEN FRAME ANTIQUE WHITE ),0.053158,0.054410,0.029653,0.557830,10.252359,0.026761,2.138522,0.953128
3,(WOODEN FRAME ANTIQUE WHITE ),(WOODEN PICTURE FRAME WHITE FINISH),0.054410,0.053158,0.029653,0.545000,10.252359,0.026761,2.080970,0.954390
4,(JUMBO BAG RED RETROSPOT),(JUMBO STORAGE BAG SUKI),0.082975,0.060640,0.028783,0.346885,5.720416,0.023751,1.438277,0.899853

In [20]:
rules.loc[rules.antecedents == rules.antecedents.iloc[5]].sort_values('confidence', ascending =False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
5,(JUMBO STORAGE BAG SUKI),(JUMBO BAG RED RETROSPOT),0.06064,0.082975,0.028783,0.474652,5.720416,0.023751,1.745558,0.878457
21,(JUMBO STORAGE BAG SUKI),(JUMBO SHOPPER VINTAGE RED PAISLEY),0.06064,0.057348,0.023913,0.394347,6.876383,0.020436,1.556423,0.909741
41,(JUMBO STORAGE BAG SUKI),(JUMBO BAG BAROQUE BLACK WHITE),0.06064,0.049839,0.021029,0.346792,6.958183,0.018007,1.454607,0.911561
53,(JUMBO STORAGE BAG SUKI),(JUMBO BAG STRAWBERRY),0.06064,0.048615,0.020186,0.332885,6.847328,0.017238,1.426117,0.909084

In [23]:
len(rules.antecedents.value_counts())

33