In [11]:
import numpy as np
import pandas as pd
from datetime import datetime
from sklearn.preprocessing import StandardScaler

import warnings
warnings.filterwarnings('ignore')

In [12]:
movies = pd.read_csv('movies.csv')
ratings = pd.read_csv('ratings.csv')

In [13]:
select_movies = ratings.movieId.value_counts().head(1000).index.to_list()
movies = movies.loc[movies.movieId.isin(select_movies)]
ratings = ratings.loc[ratings.movieId.isin(select_movies)]

In [14]:
movies.head(2)

   movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1        2    Jumanji (1995)                   Adventure|Children|Fantasy

In [15]:
ratings.head(2)

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807

In [16]:
m = movies.copy()
m['genres'] = m['genres'].str.split('|')
m = m.explode('genres')
m = m.pivot(index='movieId', columns='genres', values='title')
m = ~m.isna()
m = m.astype(int)
m.head(2)

genres,Action,Adventure,Animation,Children,Comedy,Crime,Documentary,Drama,Fantasy,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
movieId,,,,,,,,,,,,,,,,,,,
1,0,1,1,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0
2,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0

In [7]:
r = ratings.copy()

In [8]:
r['hour'] = r['timestamp'].apply(lambda x: datetime.fromtimestamp(x).hour)
r.head()

   userId  movieId  rating   timestamp  hour
0       1       16     4.0  1217897793     6
1       1       24     1.5  1217895807     5
2       1       32     4.0  1217896246     6
3       1       47     4.0  1217896556     6
4       1       50     4.0  1217896523     6

In [19]:
users = pd.read_csv('users.csv')
users

     userId  age  time_spent_per_day
0         1   16            3.976315
1         2   24            1.891303
2         3   20            4.521478
3         4   23            2.095284
4         5   35            1.759860
..      ...  ...                 ...
663     664   22            5.288101
664     665   20            5.220446
665     666   19            3.262313
666     667   17            3.674356
667     668   24            2.718718

[668 rows x 3 columns]

In [21]:
users = pd.read_csv('users.csv')
users = users.merge(r.groupby('userId').rating.mean().reset_index(), on='userId')
users = users.merge(r.groupby('userId').hour.mean().reset_index(), on='userId')
users.head(2)

   userId  age  time_spent_per_day    rating       hour
0       1   16            3.976315  3.691589   5.616822
1       2   24            1.891303  3.923077  21.000000

In [22]:
u = users.copy()
u = u.set_index('userId')
u.columns = ['age', 'time_spent_per_day', 'u_avg_rating', 'hour']

scaler = StandardScaler()
u = pd.DataFrame(scaler.fit_transform(u), columns=u.columns, index=u.index)
u.head(2)

             age  time_spent_per_day  u_avg_rating      hour
userId
1      -1.470292            0.341073     -0.073572 -0.882006
2      -0.135616           -1.079947      0.426461  1.477906

In [23]:
ratings

        userId  movieId  rating   timestamp
0            1       16     4.0  1217897793
1            1       24     1.5  1217895807
2            1       32     4.0  1217896246
3            1       47     4.0  1217896556
4            1       50     4.0  1217896523
...        ...      ...     ...         ...
105148     668   109374     4.0  1415763807
105151     668   109487     4.0  1415421771
105185     668   111759     3.0  1413728719
105205     668   112852     4.0  1433992065
105252     668   116797     4.0  1422970740

[63250 rows x 4 columns]

In [25]:
X = ratings[['movieId', 'userId', 'rating']].copy()

In [27]:
X = X.merge(u.reset_index(), on='userId', how='right')

In [29]:
X.head()

,movieId,userId,rating,age,time_spent_per_day,u_avg_rating,hour
0,16,1,4.0,-1.470292,0.341073,-0.073572,-0.882006
1,24,1,1.5,-1.470292,0.341073,-0.073572,-0.882006
2,32,1,4.0,-1.470292,0.341073,-0.073572,-0.882006
3,47,1,4.0,-1.470292,0.341073,-0.073572,-0.882006
4,50,1,4.0,-1.470292,0.341073,-0.073572,-0.882006

In [31]:
X = X.merge(m.reset_index(), on='movieId', how='right')
X

,movieId,userId,rating,age,time_spent_per_day,u_avg_rating,hour,Action,Adventure,Animation,...,Film-Noir,Horror,IMAX,Musical,Mystery,Romance,Sci-Fi,Thriller,War,Western
0,1,2,5.0,-0.135616,-1.079947,0.426461,1.477906,0,1,1,...,0,0,0,0,0,0,0,0,0,0
1,1,5,4.0,1.699565,-1.169532,-1.859363,-1.664898,0,1,1,...,0,0,0,0,0,0,0,0,0,0
2,1,8,5.0,0.364888,0.298545,0.160605,1.324497,0,1,1,...,0,0,0,0,0,0,0,0,0,0
3,1,11,4.0,-1.303458,0.513712,-0.380602,0.557454,0,1,1,...,0,0,0,0,0,0,0,0,0,0
4,1,14,4.0,-0.302450,1.251552,-0.379415,0.557454,0,1,1,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
63245,116797,606,4.0,-0.302450,1.470639,0.126240,1.491852,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63246,116797,619,4.0,0.364888,1.140836,-0.398649,0.898946,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63247,116797,622,4.0,-0.636119,-0.301899,0.350543,-0.147432,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63248,116797,642,4.0,-0.802954,-0.783329,0.719685,-0.489334,0,0,0,...,0,0,0,0,0,0,0,1,1,0
63249,116797,668,4.0,-0.135616,-0.516031,-1.470722,0.102968,0,0,0,...,0,0,0,0,0,0,0,1,1,0

In [32]:
X = X.drop(columns = ['movieId', 'userId'])
y = X.pop('rating')

In [33]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=0)

In [34]:
from sklearn.ensemble import GradientBoostingRegressor

model = GradientBoostingRegressor()
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [35]:
from sklearn.metrics import mean_squared_error as mse
mse(y_test, y_pred)**0.5

0.8868700141216211

In [36]:
ratings.loc[ratings.userId==1].head()

   userId  movieId  rating   timestamp
0       1       16     4.0  1217897793
1       1       24     1.5  1217895807
2       1       32     4.0  1217896246
3       1       47     4.0  1217896556
4       1       50     4.0  1217896523

In [38]:
#recommend movies for user 5
user id =5

SyntaxError: invalid syntax (3813949547.py, line 1)

In [39]:
u.loc[5]

age                   1.699565
time_spent_per_day   -1.169532
u_avg_rating         -1.859363
hour                 -1.664898
Name: 5, dtype: float64

In [40]:
m.loc[1]

genres
Action         0
Adventure      1
Animation      1
Children       1
Comedy         1
Crime          0
Documentary    0
Drama          0
Fantasy        1
Film-Noir      0
Horror         0
IMAX           0
Musical        0
Mystery        0
Romance        0
Sci-Fi         0
Thriller       0
War            0
Western        0
Name: 1, dtype: int64

In [41]:
model.predict(u.loc[1].append(m.loc[1]).values.reshape(1,-1))

array([3.71729074])

In [42]:
## COllabroative Filtering
from cmfrec import CMF

In [43]:
rm_raw = ratings[['userId', 'movieId', 'rating']].copy()
rm_raw.columns = ['UserId', 'ItemId', 'Rating']  # Lib requires specific column names
rm_raw.head(2)

   UserId  ItemId  Rating
0       1      16     4.0
1       1      24     1.5

In [46]:
rm_raw.shape

(63250, 3)

In [51]:
CMF?

Init signature:
CMF(
    k=40,
    lambda_=10.0,
    method='als',
    use_cg=True,
    user_bias=True,
    item_bias=True,
    center=True,
    add_implicit_features=False,
    scale_lam=False,
    scale_lam_sideinfo=False,
    scale_bias_const=False,
    k_user=0,
    k_item=0,
    k_main=0,
    w_main=1.0,
    w_user=1.0,
    w_item=1.0,
    w_implicit=0.5,
    l1_lambda=0.0,
    center_U=True,
    center_I=True,
    maxiter=800,
    niter=10,
    parallelize='separate',
    corr_pairs=4,
    max_cg_steps=3,
    precondition_cg=False,
    finalize_chol=True,
    NA_as_zero=False,
    NA_as_zero_user=False,
    NA_as_zero_item=False,
    nonneg=False,
    nonneg_C=False,
    nonneg_D=False,
    max_cd_steps=100,
    precompute_for_predictions=True,
    include_all_X=True,
    use_float=True,
    random_state=1,
    verbose=True,
    print_every=10,
    handle_interrupt=True,
    produce_dicts=False,
    nthreads=-1,
    n_jobs=None,
)
Docstring:
Collective or multi-view matrix factorization

Tries to approximate the 'X' interactions matrix  by a formula as follows:

    :math:`\mathbf{X} \sim \mathbf{A}  \mathbf{B}^T`

While at the same time also approximating the user/row side information
matrix 'U' and the item/column side information matrix 'I' as follows:

    :math:`\mathbf{U} \sim \mathbf{A} \mathbf{C}^T`,

    :math:`\mathbf{I} \sim \mathbf{B} \mathbf{D}^T`

The matrices ("A", "B", "C", "D") are obtained by minimizing the error
with respect to the non-missing entries in the input data ("X", "U", "I").
Might apply sigmoid transformations to binary columns in U and I too.

This is the most flexible of the models available in this package, and
can also mimic the implicit-feedback version through the option 'NA_as_zero'
plus an array of weights.

Note
----
The default arguments are not geared towards speed.
For faster fitting, use ``method="als"``, ``use_cg=True``,
``finalize_chol=False``, ``use_float=True``,
``precompute_for_predictions=False``, ``produce_dicts=False``,
and pass COO matrices or NumPy arrays instead of DataFrames to ``fit``.

Note
----
By default, the model optimization objective will not scale any of its
terms according to number of entries (see parameter ``scale_lam``),
so hyperparameters such as ``lambda_`` will require more tuning than
in other software and trying out values over a wider range.

Parameters
----------
k : int
    Number of latent factors to use (dimensionality of the low-rank
    factorization), which will be shared between the factorization of the
    'X' matrix and the side info matrices. Additional non-shared components
    can also be specified through ``k_user``, ``k_item``, and ``k_main``.
    Typical values are 30 to 100.
lambda_ : float or array(6,)
    Regularization parameter. Can also use different regularization for each
    matrix, in which case it should be an array with 6 entries, corresponding,
    in this order, to: user_bias, item_bias, A, B, C, D. Note that the default
    value for ``lambda_`` here is much higher than in other software, and that
    the loss/objective function is not divided by the number of entries anywhere,
    so this parameter needs good tuning.
    For example, a good value for the MovieLens10M would be ``lambda_=35.``
    (or ``lambda=0.05`` with ``scale_lam=True``).
    Typical values are :math:`10^{-2}` to :math:`10^2`.
method : str, one of "lbfgs" or "als"
    Optimization method used to fit the model. If passing ``'lbfgs'``, will
    fit it through a gradient-based approach using an L-BFGS optimizer.
    L-BFGS is typically a much slower and a much less memory efficient method
    compared to ``'als'``, but tends to reach better local optima and allows
    some variations of the problem which ALS doesn't, such as applying sigmoid
    transformations for binary side information.
use_cg : bool
    In the ALS method, whether to use a conjugate gradient method to solve
    the closed-form least squares problems. This is a faster and more
    memory-efficient alternative than the default Cholesky solver, but less
    exact, less numerically stable, and will require slightly more ALS
    iterations (``niter``) to reach a good optimum.
    In general, better results are achieved with ``use_cg=False``.
    Note that, if using this method, calculations after fitting which involve
    new data such as ``factors_warm``,  might produce slightly different
    results from the factors obtained from calling ``fit`` with the same data,
    due to differences in numerical precision. A workaround for this issue
    (factors on new data that might differ slightly) is to use
    ``finalize_chol=True``.
    Even if passing "True" here, will use the Cholesky method in cases in which
    it is faster (e.g. dense matrices with no missing values),
    and will not use the conjugate gradient method on new data.
    This option is not available when using L1 regularization and/or
    non-negativity constraints.
    Ignored when passing ``method="lbfgs"``.
user_bias : bool
    Whether to add user/row biases (intercepts) to the model.
    If using it for purposes other than recommender systems, this is is
    usually **not** suggested to include.
item_bias : bool
    Whether to add item/column biases (intercepts) to the model. Be aware that using
    item biases with low regularization for them will tend to favor items
    with high average ratings regardless of the number of ratings the item
    has received.
center : bool
    Whether to center the "X" data by subtracting the mean value. For recommender
    systems, it's highly recommended to pass "True" here, the more so if the
    model has user and/or item biases.
add_implicit_features : bool
    Whether to automatically add so-called implicit features from the data,
    as in reference [5a]_ and similar. If using this for recommender systems
    with small amounts of data, it's recommended to pass 'True' here.
scale_lam : bool
    Whether to scale (increase) the regularization parameter
    for each row of the model matrices (A, B, C, D) according
    to the number of non-missing entries in the data for that
    particular row, as proposed in reference [7a]_. For the
    A and B matrices, the regularization will only be scaled
    according to the number of non-missing entries in "X"
    (see also the ``scale_lam_sideinfo`` parameter). Note that,
    when using the options ``NA_as_zero_*``, all entries are
    considered to be non-missing. If passing "True" here, the
    optimal value for ``lambda_`` will be much smaller
    (and likely below 0.1).
    This option tends to give better results, but
    requires more hyperparameter tuning.
    Only supported for ``method="als"``.

    When generating factors based on side information alone,
    if passing ``scale_lam_sideinfo``, will regularize assuming
    there was one observation present. Be aware that using this option
    **without** ``scale_lam_sideinfo=True`` can lead to bad cold-start
    recommendations as it will set a very small regularization for
    users who have no 'X' data.

    Warning: in smaller datasets, using this option can result in top-N
    recommendations having mostly items with very few interactions (see
    parameter ``scale_bias_const``).
scale_lam_sideinfo : bool
    Whether to scale (increase) the regularization
    parameter for each row of the "A" and "B"
    matrices according to the number of non-missing
    entries in both "X" and the side info matrices
    "U" and "I". If passing "True" here, ``scale_lam``
    will also be assumed to be "True".
scale_bias_const : bool
    When passing ``scale_lam=True`` and ``user_bias=True`` or ``item_bias=True``,
    whether to apply the same scaling to the regularization **of the biases** to all
    users and items, according to the average number of non-missing entries rather
    than to the number of entries for each specific user/item.

    While this tends to result in worse RMSE, it tends to make the top-N
    recommendations less likely to select items with only a few interactions
    from only a few users.

    Ignored when passing ``scale_lam=False`` or not using user/item biases.
k_user : int
    Number of factors in the factorizing A and C matrices which will be used
    only for the 'U' and 'U_bin' matrices, while being ignored for the 'X' matrix.
    These will be the first factors of the matrices once the model is fit.
    Will be counted in addition to those already set by ``k``.
k_item : int
    Number of factors in the factorizing B and D matrices which will be used
    only for the 'I' and 'I_bin' matrices, while being ignored for the 'X' matrix.
    These will be the first factors of the matrices once the model is fit.
    Will be counted in addition to those already set by ``k``.
k_main : int
    Number of factors in the factorizing A and B matrices which will be used
    only for the 'X' matrix, while being ignored for the 'U', 'U_bin', 'I',
    and 'I_bin' matrices.
    These will be the last factors of the matrices once the model is fit.
    Will be counted in addition to those already set by ``k``.
w_main : float
    Weight in the optimization objective for the errors in the factorization
    of the 'X' matrix.
w_user : float
    Weight in the optimization objective for the errors in the factorization
    of the 'U' and 'U_bin' matrices. Ignored when passing neither 'U' nor
    'U_bin' to 'fit'.
w_item : float
    Weight in the optimization objective for the errors in the factorization
    of the 'I' and 'I_bin' matrices. Ignored when passing neither 'I' nor
    'I_bin' to 'fit'.
w_implicit : float
    Weight in the optimization objective for the errors in the factorizations
    of the implicit 'X' matrices. Note that, depending on the sparsity of the
    data, the sum of errors from these factorizations might be much larger than
    for the original 'X' and a smaller value will perform better.
    It is recommended to tune this parameter carefully.
    Ignored when passing ``add_implicit_features=False``.
l1_lambda : float or array(6,)
    Regularization parameter to apply to the L1 norm of the model matrices.
    Can also pass different values for each matrix (see ``lambda_`` for
    details). Note that, when adding L1 regularization, the model will be
    fit through a coordinate descent procedure, which is significantly
    slower than the Cholesky method with L2 regularization.
    Only supported with ``method="als"``.
    Not recommended.
center_U : bool
    Whether to center the 'U' matrix column-by-column. Be aware that this
    is a simple mean centering without regularization. One might want to
    turn this option off when using ``NA_as_zero_user=True``.
center_I : bool
    Whether to center the 'I' matrix column-by-column. Be aware that this
    is a simple mean centering without regularization. One might want to
    turn this option off when using ``NA_as_zero_item=True``.
maxiter : int
    Maximum L-BFGS iterations to perform. The procedure will halt if it
    has not converged after this number of updates. Note that, compared to
    the ohter models, fewer iterations will be required for converge
    here. Using higher regularization values might also decrease the number
    of required iterations. Pass zero for no L-BFGS iterations limit.
    If the procedure is spending hundreds of iterations
    without any significant decrease in the loss function or gradient norm,
    it's highly likely that the regularization is too low.
    Ignored when passing ``method='als'``.
niter : int
    Number of alternating least-squares iterations to perform. Note that
    one iteration denotes an update round for all the matrices rather than
    an update of a single matrix. In general, the more iterations, the better
    the end result. Ignored when passing ``method='lbfgs'``.
    Typical values are 6 to 30.
parallelize : str, "separate" or "single"
    How to parallelize gradient calculations when using more than one
    thread with ``method='lbfgs'``. Passing ``'separate'`` will iterate
    over the data twice - first
    by rows and then by columns, letting each thread calculate results
    for each row and column, whereas passing ``'single'`` will iterate over
    the data only once, and then sum the obtained results from each thread.
    Passing ``'separate'`` is much more memory-efficient and less prone to
    irreproducibility of random seeds, but might be slower for typical
    use-cases. Ignored when passing ``nthreads=1``, or ``method='als'``,
    or when compiling without OpenMP support.
corr_pairs : int
    Number of correction pairs to use for the L-BFGS optimization routine.
    Recommended values are between 3 and 7. Note that higher values
    translate into higher memory requirements. Ignored when passing
    ``method='als'``.
max_cg_steps : int
    Maximum number of conjugate gradient iterations to perform in an ALS round.
    Ignored when passing ``use_cg=False`` or ``method="lbfgs"``.
precondition_cg : bool
    Whether to use Jacobi preconditioning for the conjugate gradient procedure.
    In general, this type of preconditioning is not beneficial (makes the algorithm
    slower) as the factor variables tend to be in the same scale, but it might help
    when using non-shared factors.
    Note that, when using preconditioning, the procedure will not check for convergence,
    taking instead a fixed number of steps (given by ``max_cg_steps``) at each iteration
    regardless of whether it has reached the optimum already.
    Ignored when passing ``use_cg=False`` or ``method="als"``.
finalize_chol : bool
    When passing ``use_cg=True`` and ``method="als"``, whether to perform the last iteration with
    the Cholesky solver. This will make it slower, but will avoid the issue
    of potential mismatches between the result from ``fit`` and calls to
    ``factors_warm`` or similar with the same data.
NA_as_zero : bool
    Whether to take missing entries in the 'X' matrix as zeros (only
    when the 'X' matrix is passed as sparse COO matrix or DataFrame)
    instead of ignoring them. Note that this is a different model from the
    implicit-feedback version with weighted entries, and it's a much faster
    model to fit.
    Note that passing "True" will affect the results of the functions named
    "cold" (as it will assume zeros instead of missing).
    It is possible to obtain equivalent results to the implicit-feedback
    model if passing "True" here, and then passing an "X" to fit with
    all values set to one and weights corresponding to the actual values
    of "X" multiplied by alpha, plus 1 (W := 1 + alpha*X to imitate the
    implicit-feedback model).
    If passing this option, be aware that the defaults are also to
    perform mean centering and add user/item biases, which might
    be undesirable to have together with this option.
NA_as_zero_user : bool
    Whether to take missing entries in the 'U' matrix as zeros (only
    when the 'U' matrix is passed as sparse COO matrix) instead of ignoring them.
    Note that passing "True" will affect the results of the functions named
    "warm" if no data is passed there (as it will assume zeros instead of
    missing).
NA_as_zero_item : bool
    Whether to take missing entries in the 'I' matrix as zeros (only
    when the 'I' matrix is passed as sparse COO matrix) instead of ignoring them.
nonneg : bool
    Whether to constrain the 'A' and 'B' matrices to be non-negative.
    In order for this to work correctly, the 'X' input data must also be
    non-negative. This constraint will also be applied to the 'Ai'
    and 'Bi' matrices if passing ``add_implicit_features=True``.

    **Important:** be aware that the default options are to perform mean
    centering and to add user and item biases, which might be undesirable and
    hinder performance when having non-negativity constraints
    (especially mean centering).

    This option is not available when using the L-BFGS method.
    Note that, when determining non-negative factors, it will always
    use a coordinate descent method, regardless of the value passed
    for ``use_cg`` and ``finalize_chol``.
    When used for recommender systems, one usually wants to pass 'False' here.
    For better results, do not use centering alongside this option,
    and use a higher regularization coupled with more iterations.
nonneg_C: bool
    Whether to constrain the 'C' matrix to be non-negative.
    In order for this to work correctly, the 'U' input data must also be
    non-negative.

    Note: by default, the 'U' data will be centered by columns, which
    doesn't play well with non-negativity constraints. One will likely
    want to pass ``center_U=False`` along with this.
nonneg_D: bool
    Whether to constrain the 'D' matrix to be non-negative.
    In order for this to work correctly, the 'I' input data must also be
    non-negative.

    Note: by default, the 'I' data will be centered by columns, which
    doesn't play well with non-negativity constraints. One will likely
    want to pass ``center_I=False`` along with this.
max_cd_steps : int
    Maximum number of coordinate descent updates to perform per iteration.
    Pass zero for no limit.
    The procedure will only use coordinate descent updates when having
    L1 regularization and/or non-negativity constraints.
    This number should usually be larger than ``k``.
precompute_for_predictions : bool
    Whether to precompute some of the matrices that are used when making
    predictions from the model. If 'False', it will take longer to generate
    predictions or top-N lists, but will use less memory and will be faster
    to fit the model. If passing 'False', can be recomputed later on-demand
    through method 'force_precompute_for_predictions'.
include_all_X : bool
    When passing an input "X" to ``fit`` which has less columns than rows in
    "I", whether to still make calculations about the items which are in "I"
    but not in "X". This has three effects: (a) the ``topN`` functionality may
    recommend such items, (b) the precomptued matrices will be less usable as
    they will include all such items, (c) it will be possible to pass "X" data
    to the new factors or topN functions that include such columns (rows of "I").
    This option is ignored when using ``NA_as_zero``.
use_float : bool
    Whether to use C float type for the model parameters (typically this is
    ``np.float32``). If passing ``False``, will use C double (typically this
    is ``np.float64``). Using float types will speed up computations and
    use less memory, at the expense of reduced numerical precision.
random_state : int, RandomState, Generator, or None
    Seed used to initialize parameters at random. If passing a NumPy
    RandomState or Generator, will use it to draw a random integer. Note
    however that, if using more than one thread, results might not be
    100% reproducible with ``method='lbfgs'`` due to round-off errors
    in parallelized aggregations.
    If passing ``None``, will draw a non-reproducible random integer
    to use as seed.
verbose : bool
    Whether to print informational messages about the optimization
    routine used to fit the model. Be aware that, if passing 'False' and
    ``method='lbfgs'``, the optimization routine will not respond to
    interrupt signals.
print_every : int
    Print L-BFGS convergence messages every n-iterations. Ignored
    when passing ``verbose=False`` or ``method='als'``.
produce_dicts : bool
    Whether to produce Python dicts from the mappings between user/item
    IDs passed to 'fit' and the internal IDs used by the class. Having
    these dicts might speed up some computations such as 'predict',
    but it will add some extra overhead at the time of fitting the model
    and extra memory usage. Ignored when passing the data as matrices
    and arrays instead of data frames.
handle_interrupt : bool

In [44]:
model = CMF(method="als", k=2, lambda_=0.1, user_bias=False, item_bias=False, verbose=False)
model.fit(rm_raw)

Collective matrix factorization model
(explicit-feedback variant)

In [47]:
model.A_.shape

(668, 2)

In [48]:
model.B_.shape

(1000, 2)

In [49]:
rm_raw.Rating.mean(),model.glob_mean_

(3.6659130434782607, 3.6659131050109863)

In [50]:
top_items = model.topN(user=1, n=10)
movies.loc[movies.movieId.isin(top_items)]

,movieId,title,genres
279,318,"Shawshank Redemption, The (1994)",Crime|Drama
743,922,Sunset Blvd. (a.k.a. Sunset Boulevard) (1950),Drama|Film-Noir|Romance
744,923,Citizen Kane (1941),Drama|Mystery
938,1172,Cinema Paradiso (Nuovo cinema Paradiso) (1989),Drama
973,1212,"Third Man, The (1949)",Film-Noir|Mystery|Thriller
978,1217,Ran (1985),Drama|War
4472,5971,My Neighbor Totoro (Tonari no Totoro) (1988),Animation|Children|Drama|Fantasy
5390,7502,Band of Brothers (2001),Action|Drama|War
6958,44555,"Lives of Others, The (Das leben der Anderen) (...",Drama|Romance|Thriller
9908,109374,"Grand Budapest Hotel, The (2014)",Comedy|Drama

In [ ]:
rm_raw = ratings[['userId', 'movieId', 'rating']].copy()
rm_raw.columns = ['UserId', 'ItemId', 'Rating']  # Lib requires specific column names
model = CMF(method="als", k=2, lambda_=0.1, user_bias=False, item_bias=False, verbose=False)
model.fit(rm_raw)
top_items = model.topN(user=1, n=10)